
import React, { useState, useEffect } from 'react';
import { User } from '../types';
import { userService } from '../services/userService';
import { translations } from '../translations';
import Logo from './Logo';
import { User as UserIcon, Mail, Phone, Lock, ArrowRight, ArrowLeft, CheckCircle, RefreshCcw } from 'lucide-react';
import { useToast } from './ToastProvider';

interface RegisterCustomerProps {
  onRegister: (user: User) => void;
  onBackToLogin: () => void;
}

const RegisterCustomer: React.FC<RegisterCustomerProps> = ({ onRegister, onBackToLogin }) => {
  const [lang, setLang] = useState<'ar' | 'en'>('ar');
  const { showToast } = useToast();
  
  useEffect(() => {
    setLang(document.documentElement.lang === 'en' ? 'en' : 'ar');
  }, []);

  const t = translations[lang];
  const isRtl = lang === 'ar';

  // State Machine: FORM -> VERIFY
  const [step, setStep] = useState<'FORM' | 'VERIFY'>('FORM');
  const [verificationCode, setVerificationCode] = useState('');

  const [formData, setFormData] = useState({
    name: '',
    email: '',
    phone: '',
    password: '',
    confirmPassword: ''
  });
  
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [focusedField, setFocusedField] = useState<string | null>(null);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
    if (error) setError('');
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError('');
    
    // Validation
    if (!formData.name || !formData.email || !formData.password || !formData.phone) {
      const msg = lang === 'en' ? 'All fields are required' : 'جميع الحقول مطلوبة';
      setError(msg);
      showToast(msg, 'warning');
      setLoading(false);
      return;
    }

    if (formData.password !== formData.confirmPassword) {
      const msg = lang === 'en' ? 'Passwords do not match' : 'كلمات المرور غير متطابقة';
      setError(msg);
      showToast(msg, 'error');
      setLoading(false);
      return;
    }

    const newUser: User = {
      id: '', // Generated by service
      name: formData.name,
      email: formData.email,
      phone: formData.phone,
      role: 'CUSTOMER',
      status: 'PENDING',
      isApproved: false,
      createdAt: Date.now(),
    };

    const result = await userService.register(newUser, formData.password);

    if (result.success) {
      if (result.requiresVerification) {
        setStep('VERIFY');
        showToast(lang === 'en' ? 'Registration successful. Check email for code.' : 'تم التسجيل. تحقق من بريدك للحصول على الرمز.', 'info');
      } else if (result.data) {
        showToast(t.common.success, 'success');
        onRegister(result.data.user);
      }
    } else {
      const msg = result.error || (lang === 'en' ? 'Registration failed' : 'فشل التسجيل');
      setError(msg);
      showToast(msg, 'error');
    }
    setLoading(false);
  };

  const handleVerify = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError('');

    const result = await userService.verifyEmail(formData.email, verificationCode);
    if (result.success && result.data) {
      showToast(lang === 'en' ? 'Account Verified!' : 'تم تأكيد الحساب!', 'success');
      onRegister(result.data.user);
    } else {
      setError(result.error || (lang === 'en' ? 'Verification failed' : 'فشل التحقق'));
      showToast(result.error || 'Failed', 'error');
    }
    setLoading(false);
  };

  const handleResend = async () => {
    setLoading(true);
    const result = await userService.resendVerificationCode(formData.email);
    if (result.success) {
      showToast(lang === 'en' ? 'Code sent!' : 'تم إرسال الرمز!', 'success');
    } else {
      showToast(result.error || 'Error', 'error');
    }
    setLoading(false);
  };

  // Helper for Input Field
  const InputField = ({ 
    name, 
    type = "text", 
    label, 
    placeholder, 
    icon: Icon 
  }: { name: string, type?: string, label: string, placeholder: string, icon: any }) => (
    <div className="space-y-2 group">
      <label className={`text-[10px] font-black uppercase tracking-widest transition-colors duration-300 ${focusedField === name ? 'text-palma-primary' : 'text-slate-400'}`}>
        {label}
      </label>
      <div className={`relative flex items-center bg-slate-50 border-2 rounded-2xl transition-all duration-300 ${focusedField === name ? 'border-palma-primary bg-white shadow-soft' : 'border-transparent hover:bg-slate-100'}`}>
        <div className={`p-4 ${focusedField === name ? 'text-palma-primary' : 'text-slate-400'}`}>
          <Icon className="w-5 h-5 transition-colors" />
        </div>
        <input 
          required 
          type={type} 
          name={name} 
          className="w-full bg-transparent p-4 pl-0 rtl:pr-0 rtl:pl-4 text-sm font-bold text-slate-900 outline-none placeholder:text-slate-300 placeholder:font-normal"
          placeholder={placeholder}
          value={formData[name as keyof typeof formData]} 
          onChange={handleChange}
          onFocus={() => setFocusedField(name)}
          onBlur={() => setFocusedField(null)}
        />
      </div>
    </div>
  );

  return (
    <div className="min-h-screen flex bg-white font-sans text-slate-900" dir={isRtl ? 'rtl' : 'ltr'}>
      
      {/* Left Side: Form */}
      <div className="w-full lg:w-1/2 flex flex-col justify-center p-8 sm:p-16 lg:p-24 relative z-10">
        <div className="max-w-md w-full mx-auto space-y-10 animate-in slide-in-from-bottom-8 duration-700">
          
          {step === 'FORM' ? (
            <>
              {/* Header */}
              <div className="space-y-3">
                <div className="inline-block mb-4" onClick={onBackToLogin}>
                   <Logo size="small" />
                </div>
                <h1 className="text-4xl font-black text-palma-navy tracking-tight leading-tight">
                  {lang === 'en' ? 'Create Account' : 'إنشاء حساب جديد'}
                </h1>
                <p className="text-slate-400 font-bold text-xs uppercase tracking-widest">
                  {t.auth.customerSubtitle}
                </p>
              </div>

              {/* Error Message */}
              {error && (
                <div className="p-4 bg-red-50 border border-red-100 text-red-600 text-xs font-bold rounded-2xl flex items-center gap-3 animate-in shake">
                  <span className="w-2 h-2 rounded-full bg-red-500 shrink-0" />
                  {error}
                </div>
              )}

              <form onSubmit={handleSubmit} className="space-y-6">
                <InputField 
                  name="name" 
                  label={t.auth.name} 
                  placeholder={lang === 'en' ? "Your full name" : "الاسم الكامل"} 
                  icon={UserIcon} 
                />
                
                <InputField 
                  name="email" 
                  type="email"
                  label={t.auth.email} 
                  placeholder="name@example.com" 
                  icon={Mail} 
                />

                <InputField 
                  name="phone" 
                  type="tel"
                  label={t.auth.phone} 
                  placeholder="05x-xxxxxxx" 
                  icon={Phone} 
                />

                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <InputField 
                    name="password" 
                    type="password"
                    label={t.auth.password} 
                    placeholder="••••••••" 
                    icon={Lock} 
                  />
                  <InputField 
                    name="confirmPassword" 
                    type="password"
                    label={lang === 'en' ? 'Confirm Password' : 'تأكيد كلمة المرور'} 
                    placeholder="••••••••" 
                    icon={Lock} 
                  />
                </div>

                <div className="pt-6 space-y-6">
                  <button 
                    type="submit" 
                    disabled={loading} 
                    className="w-full py-5 bg-palma-primary text-white rounded-2xl font-black uppercase text-[11px] tracking-widest shadow-xl shadow-palma-primary/30 hover:bg-emerald-800 hover:scale-[1.01] transition-all active:scale-[0.98] disabled:opacity-70 disabled:cursor-not-allowed flex items-center justify-center gap-3 group"
                  >
                    {loading ? (
                      <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                    ) : (
                      <>
                        {lang === 'en' ? 'Sign Up Now' : 'تسجيل الحساب'}
                        {isRtl ? <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" /> : <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />}
                      </>
                    )}
                  </button>

                  <button 
                    type="button" 
                    onClick={onBackToLogin} 
                    className="w-full text-center text-xs font-bold text-slate-400 hover:text-palma-navy transition-colors uppercase tracking-wider"
                  >
                    {t.common.back}
                  </button>
                </div>
              </form>
            </>
          ) : (
            /* VERIFICATION STEP */
            <div className="text-center animate-in fade-in zoom-in duration-500">
               <div className="w-20 h-20 bg-palma-green/10 text-palma-green rounded-full flex items-center justify-center mx-auto mb-6">
                  <Mail className="w-8 h-8" />
               </div>
               <h2 className="text-2xl font-black text-slate-900 mb-2">{lang === 'en' ? 'Verify Email' : 'تحقق من البريد الإلكتروني'}</h2>
               <p className="text-slate-500 text-sm mb-6">{lang === 'en' ? `We sent a code to ${formData.email}` : `أرسلنا رمزاً إلى ${formData.email}`}</p>
               
               <form onSubmit={handleVerify} className="space-y-6 max-w-xs mx-auto">
                  <input 
                    autoFocus
                    required
                    type="text" 
                    maxLength={6}
                    className="w-full p-5 text-center text-2xl font-black tracking-[0.5em] rounded-2xl border-2 border-slate-200 focus:border-palma-green outline-none transition-all placeholder:text-slate-200"
                    value={verificationCode}
                    onChange={e => setVerificationCode(e.target.value.replace(/[^0-9]/g, ''))}
                    placeholder="000000"
                  />
                  
                  {error && <p className="text-red-500 text-xs font-bold">{error}</p>}

                  <div className="flex flex-col gap-3">
                    <button type="submit" disabled={loading || verificationCode.length < 6} className="w-full py-4 bg-palma-primary text-white rounded-2xl font-black uppercase text-[11px] tracking-widest shadow-xl disabled:opacity-50 hover:bg-emerald-800 transition-all">
                       {loading ? t.common.loading : (lang === 'en' ? 'Verify & Login' : 'تأكيد ودخول')}
                    </button>
                    
                    <button type="button" onClick={handleResend} disabled={loading} className="w-full py-3 bg-white text-slate-400 border border-slate-200 rounded-2xl text-[10px] font-black uppercase tracking-widest hover:bg-slate-50 transition-all">
                       {lang === 'en' ? 'Resend Code' : 'إعادة إرسال الرمز'}
                    </button>
                  </div>
               </form>

               <button onClick={() => setStep('FORM')} className="mt-8 text-xs font-bold text-slate-400 hover:text-palma-navy flex items-center justify-center gap-2 mx-auto">
                 <RefreshCcw className="w-3 h-3" /> {lang === 'en' ? 'Change Email' : 'تغيير البريد'}
               </button>
            </div>
          )}
        </div>
      </div>

      {/* Right Side: Visual (Desktop Only) */}
      <div className="hidden lg:block lg:w-1/2 relative overflow-hidden bg-palma-navy">
        <div className="absolute inset-0 bg-gradient-to-br from-palma-navy via-palma-navy to-palma-primary opacity-90 z-10" />
        <img 
          src="https://images.unsplash.com/photo-1483985988355-763728e1935b?q=80&w=2070&auto=format&fit=crop" 
          className="absolute inset-0 w-full h-full object-cover mix-blend-overlay opacity-50 z-0"
          alt="Shopping Lifestyle"
        />
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 z-20 text-center text-white space-y-8 max-w-lg">
           <div className="w-24 h-24 bg-white/10 backdrop-blur-md rounded-[2rem] flex items-center justify-center mx-auto border border-white/20 shadow-2xl">
              <span className="text-5xl">✨</span>
           </div>
           <div>
             <h2 className="text-5xl font-black tracking-tighter mb-4 leading-tight">
               {lang === 'en' ? 'Join the Exclusive Marketplace' : 'انضم إلى السوق الحصري'}
             </h2>
             <p className="text-white/70 text-sm font-medium leading-relaxed">
               {lang === 'en' 
                 ? 'Access thousands of premium products from top-rated local merchants.' 
                 : 'تمتع بالوصول إلى آلاف المنتجات المميزة من أفضل التجار المحليين.'}
             </p>
           </div>
        </div>
      </div>

    </div>
  );
};

export default RegisterCustomer;
